"""The seeded PRNG, checked against output captured from the TypeScript sim.

These vectors are not invented: they were generated by the mulberry32 in the
original `api/src/sim/rng.ts` before the port, so they prove the transliteration
reproduces the generator exactly rather than merely producing *a* deterministic
sequence. Getting the 32-bit masking wrong would still look deterministic.
"""

import json

import pytest

from app.sim.rng import create_rng, rng_from_state

# seed -> first twelve draws, captured from the TypeScript implementation.
GOLDEN = {
    0: [
        1144304738,
        1416247,
        958946056,
        627933444,
        2007157716,
        2340967985,
        2642484575,
        2787370982,
        1958536065,
        2496316458,
        1057668038,
        420269829,
    ],
    1: [
        2693262067,
        11749833,
        2265367787,
        4213581821,
        4159151403,
        1207330352,
        2632122864,
        3095568220,
        1828783984,
        4272732017,
        1955374602,
        2099329838,
    ],
    12345: [
        4207900869,
        1317490944,
        2079646450,
        3513001552,
        2187978186,
        1492380277,
        316786230,
        3291647763,
        4281336957,
        3543444592,
        1975405240,
        4062369846,
    ],
    2147483647: [
        1842962257,
        546041740,
        1654754255,
        1702490205,
        513796057,
        4093909556,
        2923511389,
        4276844688,
        1536700890,
        1246778341,
        2313136311,
        3952417347,
    ],
    -7: [
        1860010037,
        1397564179,
        2337619704,
        2062400319,
        209248909,
        176908872,
        1150894308,
        885613863,
        3727111222,
        3565343962,
        520781624,
        159994118,
    ],
}


@pytest.mark.parametrize("seed", list(GOLDEN))
def test_reproduces_the_typescript_sequence(seed: int) -> None:
    rng = create_rng(seed)

    assert [rng.next_uint32() for _ in range(12)] == GOLDEN[seed]


def test_a_negative_seed_wraps_the_same_way_javascript_does() -> None:
    """`-7 | 0` in JS is the bit pattern 0xFFFFFFF9; masking must agree."""
    assert create_rng(-7).next_uint32() == GOLDEN[-7][0]


def test_the_same_seed_gives_the_same_sequence() -> None:
    assert create_rng(99).next_uint32() == create_rng(99).next_uint32()


def test_a_different_seed_gives_a_different_sequence() -> None:
    assert create_rng(1).next_uint32() != create_rng(2).next_uint32()


def test_floats_land_in_the_unit_interval() -> None:
    rng = create_rng(99)

    for _ in range(200):
        value = rng.next_float()
        assert 0.0 <= value < 1.0


def test_integers_land_below_the_exclusive_bound() -> None:
    rng = create_rng(7)

    for _ in range(200):
        value = rng.next_int(6)
        assert isinstance(value, int)
        assert 0 <= value < 6


def test_rejects_a_bound_that_is_not_a_positive_integer() -> None:
    with pytest.raises(ValueError, match="positive integer"):
        create_rng(1).next_int(0)


def test_resumes_the_sequence_a_captured_state_left_off_at() -> None:
    original = create_rng(2024)
    original.next_uint32()
    original.next_uint32()

    resumed = rng_from_state(original.state)

    assert resumed.next_uint32() == original.next_uint32()


def test_state_is_a_plain_serialisable_integer() -> None:
    rng = create_rng(31)
    rng.next_uint32()

    assert isinstance(rng.state, int)
    assert json.loads(json.dumps({"state": rng.state}))["state"] == rng.state
