"""The battle sim.

Everything a caller needs is here; nothing here touches the outside world. The
server hands `run_battle` a map, the school configs, a battle's roster data, and a
seed, and gets back the whole battle — tick by tick, with its event stream.

**side** first — resonance is a property of a player's roster rather than of the
and abilities JQ-288. See `phases/__init__.py` for where each of them attaches.
attaches.
dissolve inside `phases/removal.py`) and filled in the per-school multiplier
field — so a system reads `ctx.multipliers[unit.side][school]`.
record from the resonance curve (`resonance.py`). That record is now keyed by
resummoning and resonance JQ-289. See `phases/__init__.py` for where each of them
Slice D added resummoning and the troop bond (`phases/resummon.py`, and the
Slices A (JQ-286) and B (JQ-287) of the sim. Energy and abilities are JQ-288,
Slices A (JQ-286) and D (JQ-289) of the sim. Orders and zones are JQ-287, energy

Shared unit behavior — creature profiles, mage personalities, and the
deterministic decision loop that reads them — is JQ-328, in `ai/`. A battle that
ships no behavior library runs without it and behaves exactly as slice A did.

Two Python rules hold the determinism guarantee, neither of which had an
equivalent in the TypeScript this was ported from:

* Never iterate an unordered collection. `PYTHONHASHSEED` is randomised per
  interpreter, so `set` order differs between processes — invisible to any test
  that runs in one. Sets are used for membership only.
* Never use module-level `random`; it is process-global. Randomness comes from an
  explicit `Rng` threaded through the tick context.
"""

from app.sim.abilities import (
    EMPTY_ABILITY_CATALOG,
    Ability,
    AbilityCatalog,
    build_ability_catalog,
)
from app.sim.ai.attach import attach_behavior
from app.sim.ai.candidates import Candidate, generate_candidates
from app.sim.ai.capabilities import Capabilities, capabilities_of, supports
from app.sim.ai.coordination import (
    CoordinationProfile,
    assignment_for,
    baseline_profile,
    compose_profile,
    coordinate,
    leading_mage,
    nominated_target_ids,
    profile_for,
)
from app.sim.ai.decide import Decision, decide, intent_of
from app.sim.ai.factors import (
    FACTORS,
    FactorContribution,
    FactorName,
    FactorWeights,
    PersonalityInfluence,
)
from app.sim.ai.fixtures import (
    FIVE_PACKAGES,
    combined_library,
    contrasting_library,
    placeholder_behavior,
    sample_library,
    strength_library,
)
from app.sim.ai.intent import ActionKind, Assignment, Intent, TroopCoordination, UnitAi
from app.sim.ai.observe import Observation, observe
from app.sim.ai.profiles import (
    BehaviorLibrary,
    CoordinationInfluence,
    CreatureProfile,
    MagePersonality,
    PersonalityDefinition,
    PersonalityRef,
    PersonalityRule,
    PersonalitySource,
    PersonalityTag,
    ResolvedBehavior,
    ResolvedPersonality,
    TraitDefinition,
    TraitTag,
    UnitBehavior,
    defaulted,
    describe_behavior,
)
from app.sim.ai.scoring import ScoredCandidate, contextual_weights, score_candidates
from app.sim.ai.situation import holds
from app.sim.ai.vocabulary import CONTEXTS, Context
from app.sim.blocking import blockers_against, clamp_to_blockers
from app.sim.casting import (
    DEFAULT_CAST_POLICY,
    AimedCast,
    CastPolicy,
    FirstUsefulMoment,
    ability_ready,
)
from app.sim.config import (
    DEFAULT_SIM_CONFIG,
    SimConfig,
    max_ticks,
    seconds_per_tick,
    to_ticks,
    validate_sim_config,
)
from app.sim.context import TickContext, create_tick_context
from app.sim.effects import (
    CAST_ORIGINS,
    ORIGIN_SELF,
    ORIGIN_TARGET,
    AreaDamage,
    Burn,
    BurningGround,
    CastOrigin,
    DamageProfile,
    DashToTarget,
    Effect,
    EnergyRefill,
    Knockback,
)
from app.sim.energy import (
    ALLY_DEFEATED,
    ARTIFICE_CLOCK,
    BASELINE_TRICKLE,
    DAMAGE_DEALT,
    DAMAGE_TAKEN,
    DEFAULT_ENERGY_RULES,
    ELAPSED_SECONDS,
    ENERGY_METERS,
    EnergyMeter,
    EnergyRule,
    EnergySource,
    SchoolEnergyRuleTable,
    energy_gain,
    energy_multiplier_for,
    energy_rule_for,
    new_energy_meters,
    per_ally_defeated,
    per_damage_dealt,
    per_damage_taken,
    per_second,
    resolve_school_energy_rules,
    rule_from_rates,
)
from app.sim.events import (
    BattleEvent,
    BattleEventType,
    EventActors,
    EventEmitter,
    EventSwing,
    ability_cast,
    create_event_emitter,
    resummoned,
    spell_cast,
    troop_dissolved,
    unit_defeated,
)
from app.sim.fixtures import (
    ABILITY_UNIT_TYPES,
    PLACEHOLDER_ABILITIES,
    PLACEHOLDER_SPELLS,
    PLACEHOLDER_UNIT_TYPES,
    ability_battle,
    placeholder_battle,
)
from app.sim.formation import (
    FORMATION_RANK_GAP,
    FORMATION_SPACING,
    MAGE_SETBACK_GUARDED,
    MAGE_SETBACK_PUSH,
    Formation,
    deployment_anchor,
    deployment_band,
    derive_formation,
    station,
)
from app.sim.map import (
    TWO_LANE_MAP,
    BaseConfig,
    ChipReserve,
    DeploymentStrip,
    MapConfig,
    ZoneConfig,
    chip_box,
    clear_of_chip,
    hotspot_box,
    hotspot_centre,
    hotspot_contains,
    strip_centre,
    validate_map_config,
    zone_by_id,
    zone_centre,
    zone_containing,
)
from app.sim.orders import (
    DEFEND_BASE,
    PUSH_ENEMY_BASE,
    Order,
    OrderKind,
    anchors_on_mage,
    hold,
    legal_orders,
    may_attack_base,
    objective_position,
    validate_order,
)
from app.sim.phase import TickPhase
from app.sim.phases import TICK_PHASES
from app.sim.resolution import Cast, EffectOutcome, apply_effects, damage_unit, swing_of
from app.sim.resonance import (
    STAT_AXES,
    ResonanceCounts,
    SideResonanceCounts,
    count_resonance,
)
from app.sim.rng import Rng, create_rng, rng_from_state
from app.sim.run_battle import (
    BattleOutcome,
    BattleResult,
    BattleTick,
    run_battle,
    step_battle,
)
from app.sim.schools import (
    DEFAULT_RESONANCE_CURVE,
    IDENTITY_MULTIPLIERS,
    SCHOOLS,
    ResonanceCurve,
    School,
    SchoolConfig,
    SchoolMultipliers,
    SchoolMultiplierTable,
    SideMultiplierTable,
    resolve_school_multipliers,
    resolve_side_multipliers,
    resonance_step,
)
from app.sim.serialize import digest_battle, serialize_battle
from app.sim.spells import (
    EMPTY_SPELL_CATALOG,
    Spell,
    SpellCatalog,
    SpellInjection,
    build_spell_catalog,
    schedule_injections,
)
from app.sim.statuses import BURNING_GROUND, BurnStatus, GroundHazard
from app.sim.types import SIDES, Side, Span, TroopId, UnitId, UnitRef, Vec2, opposing
from app.sim.units import UnitKind, UnitType, UnitTypeCatalog, build_unit_type_catalog
from app.sim.world import (
    ArmySetup,
    BaseState,
    BattleSetup,
    DispelledSlot,
    RosterEntry,
    Troop,
    TroopSetup,
    Unit,
    World,
    create_world,
    is_alive,
    is_resummonable,
    order_of,
    orders_by_troop,
    support_capacity_of,
    survives_round_end,
    troop_of,
    unit_ref,
)
from app.sim.zones import ZoneOccupancy, zone_occupancy

__all__ = [
    "ABILITY_UNIT_TYPES",
    "ALLY_DEFEATED",
    "ARTIFICE_CLOCK",
    "BASELINE_TRICKLE",
    "BURNING_GROUND",
    "CAST_ORIGINS",
    "CONTEXTS",
    "DAMAGE_DEALT",
    "DAMAGE_TAKEN",
    "DEFAULT_CAST_POLICY",
    "DEFAULT_ENERGY_RULES",
    "DEFAULT_RESONANCE_CURVE",
    "DEFAULT_SIM_CONFIG",
    "DEFEND_BASE",
    "ELAPSED_SECONDS",
    "EMPTY_ABILITY_CATALOG",
    "EMPTY_SPELL_CATALOG",
    "ENERGY_METERS",
    "FACTORS",
    "FIVE_PACKAGES",
    "FORMATION_RANK_GAP",
    "FORMATION_SPACING",
    "IDENTITY_MULTIPLIERS",
    "MAGE_SETBACK_GUARDED",
    "MAGE_SETBACK_PUSH",
    "ORIGIN_SELF",
    "ORIGIN_TARGET",
    "PLACEHOLDER_ABILITIES",
    "PLACEHOLDER_SPELLS",
    "PLACEHOLDER_UNIT_TYPES",
    "PUSH_ENEMY_BASE",
    "SCHOOLS",
    "SIDES",
    "STAT_AXES",
    "TICK_PHASES",
    "TWO_LANE_MAP",
    "Ability",
    "AbilityCatalog",
    "ActionKind",
    "AimedCast",
    "AreaDamage",
    "ArmySetup",
    "Assignment",
    "BaseConfig",
    "BaseState",
    "BattleEvent",
    "BattleEventType",
    "BattleOutcome",
    "BattleResult",
    "BattleSetup",
    "BattleTick",
    "BehaviorLibrary",
    "Burn",
    "BurnStatus",
    "BurningGround",
    "Candidate",
    "Capabilities",
    "Cast",
    "CastOrigin",
    "CastPolicy",
    "ChipReserve",
    "Context",
    "CoordinationInfluence",
    "CoordinationProfile",
    "CreatureProfile",
    "DamageProfile",
    "DashToTarget",
    "Decision",
    "DeploymentStrip",
    "DispelledSlot",
    "Effect",
    "EffectOutcome",
    "EnergyMeter",
    "EnergyRefill",
    "EnergyRule",
    "EnergySource",
    "EventActors",
    "EventEmitter",
    "EventSwing",
    "FactorContribution",
    "FactorName",
    "FactorWeights",
    "FirstUsefulMoment",
    "Formation",
    "GroundHazard",
    "Intent",
    "Knockback",
    "MagePersonality",
    "MapConfig",
    "Observation",
    "Order",
    "OrderKind",
    "PersonalityDefinition",
    "PersonalityInfluence",
    "PersonalityRef",
    "PersonalityRule",
    "PersonalitySource",
    "PersonalityTag",
    "ResolvedBehavior",
    "ResolvedPersonality",
    "ResonanceCounts",
    "ResonanceCurve",
    "Rng",
    "RosterEntry",
    "School",
    "SchoolConfig",
    "SchoolEnergyRuleTable",
    "SchoolMultiplierTable",
    "SchoolMultipliers",
    "ScoredCandidate",
    "Side",
    "SideMultiplierTable",
    "SideResonanceCounts",
    "SimConfig",
    "Span",
    "Spell",
    "SpellCatalog",
    "SpellInjection",
    "TickContext",
    "TickPhase",
    "TraitDefinition",
    "TraitTag",
    "Troop",
    "TroopCoordination",
    "TroopId",
    "TroopSetup",
    "Unit",
    "UnitAi",
    "UnitBehavior",
    "UnitId",
    "UnitKind",
    "UnitRef",
    "UnitType",
    "UnitTypeCatalog",
    "Vec2",
    "World",
    "ZoneConfig",
    "ZoneOccupancy",
    "ability_battle",
    "ability_cast",
    "ability_ready",
    "anchors_on_mage",
    "apply_effects",
    "assignment_for",
    "attach_behavior",
    "baseline_profile",
    "blockers_against",
    "build_ability_catalog",
    "build_spell_catalog",
    "build_unit_type_catalog",
    "capabilities_of",
    "chip_box",
    "clamp_to_blockers",
    "clear_of_chip",
    "combined_library",
    "compose_profile",
    "contextual_weights",
    "contrasting_library",
    "coordinate",
    "count_resonance",
    "create_event_emitter",
    "create_rng",
    "create_tick_context",
    "create_world",
    "damage_unit",
    "decide",
    "defaulted",
    "deployment_anchor",
    "deployment_band",
    "derive_formation",
    "describe_behavior",
    "digest_battle",
    "energy_gain",
    "energy_multiplier_for",
    "energy_rule_for",
    "generate_candidates",
    "hold",
    "holds",
    "hotspot_box",
    "hotspot_centre",
    "hotspot_contains",
    "intent_of",
    "is_alive",
    "is_resummonable",
    "leading_mage",
    "legal_orders",
    "max_ticks",
    "may_attack_base",
    "new_energy_meters",
    "nominated_target_ids",
    "objective_position",
    "observe",
    "opposing",
    "order_of",
    "orders_by_troop",
    "per_ally_defeated",
    "per_damage_dealt",
    "per_damage_taken",
    "per_second",
    "placeholder_battle",
    "placeholder_behavior",
    "profile_for",
    "resolve_school_energy_rules",
    "resolve_school_multipliers",
    "resolve_side_multipliers",
    "resonance_step",
    "resummoned",
    "rng_from_state",
    "rule_from_rates",
    "run_battle",
    "sample_library",
    "schedule_injections",
    "score_candidates",
    "seconds_per_tick",
    "serialize_battle",
    "spell_cast",
    "station",
    "step_battle",
    "strength_library",
    "strip_centre",
    "support_capacity_of",
    "supports",
    "survives_round_end",
    "swing_of",
    "to_ticks",
    "troop_dissolved",
    "troop_of",
    "unit_defeated",
    "unit_ref",
    "validate_map_config",
    "validate_order",
    "validate_sim_config",
    "zone_by_id",
    "zone_centre",
    "zone_containing",
    "zone_occupancy",
]
